FROM openmrs/openmrs-core:2.7.0-amazoncorretto-11

COPY legacyui-omod-1.22.0.jar /openmrs/data/modules/legacyui.omod
COPY webservices.rest-omod-2.48.0.jar /openmrs/data/modules/webservices.rest.omod
COPY consultationworkflow-omod-1.0.0-SNAPSHOT.jar /openmrs/data/modules/consultationworkflow.omod
